[project]
name = "periodic-gas-tool"
authors = ["Developer <developer@example.com>"]
description = "A Clarity smart contract utility for periodic gas consumption tracking and optimization"
telemetry = false
requirements = []

[contracts.gas-tracker-core]
path = "contracts/gas-tracker-core.clar"
depends_on = []

[contracts.gas-tracker-analytics]
path = "contracts/gas-tracker-analytics.clar"
depends_on = ["gas-tracker-core"]

[contracts.gas-tracker-admin]
path = "contracts/gas-tracker-admin.clar"
depends_on = ["gas-tracker-core", "gas-tracker-analytics"]

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
